// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSsaEFqbW-1kt2IvzWaJVysGZgA6HF9pA',
    appId: '1:95327148492:web:931036c9dbd5b2d3ee6569',
    messagingSenderId: '95327148492',
    projectId: 'rick-and-morty-11acd',
    authDomain: 'rick-and-morty-11acd.firebaseapp.com',
    storageBucket: 'rick-and-morty-11acd.firebasestorage.app',
    measurementId: 'G-QJEFQBB511',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2SHgmvcpIKejcY4pCgAOsCNaCB97MUhU',
    appId: '1:95327148492:android:1009873fe95f420eee6569',
    messagingSenderId: '95327148492',
    projectId: 'rick-and-morty-11acd',
    storageBucket: 'rick-and-morty-11acd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPyH40etQIDNa73J3k0EzSOWMiXCzBRHk',
    appId: '1:95327148492:ios:1d1589991ead0975ee6569',
    messagingSenderId: '95327148492',
    projectId: 'rick-and-morty-11acd',
    storageBucket: 'rick-and-morty-11acd.firebasestorage.app',
    iosBundleId: 'dev.chuvasov.rickAndMorty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPyH40etQIDNa73J3k0EzSOWMiXCzBRHk',
    appId: '1:95327148492:ios:1d1589991ead0975ee6569',
    messagingSenderId: '95327148492',
    projectId: 'rick-and-morty-11acd',
    storageBucket: 'rick-and-morty-11acd.firebasestorage.app',
    iosBundleId: 'dev.chuvasov.rickAndMorty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSsaEFqbW-1kt2IvzWaJVysGZgA6HF9pA',
    appId: '1:95327148492:web:1d6cee006a489db3ee6569',
    messagingSenderId: '95327148492',
    projectId: 'rick-and-morty-11acd',
    authDomain: 'rick-and-morty-11acd.firebaseapp.com',
    storageBucket: 'rick-and-morty-11acd.firebasestorage.app',
    measurementId: 'G-HRMQCYXLGN',
  );

}